### ISSUE TITLE
[FEATURE] Create reservation table in DB

### ISSUE THREAD

**Issue by demurelebowski** [demurelebowski/asd-java-intern#32]
**Feature description**
Create reservation table in DB. SQL query:

CREATE TABLE reservation (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    organization_id int NOT NULL,
    agent_id int NOT NULL,
    customer_id int NOT NULL,
    product_id int NOT NULL,
    state varchar(15) NOT NULL DEFAULT 'Initial',
    from_date date NOT NULL,
    to_date date NOT NULL,
    price double NOT NULL,
    quote double NOT NULL,
    currency varchar(3) NOT NULL,
    guests tinyint NOT NULL DEFAULT 1,
    notes text,
    version timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

**Comment by rdovgan** [comment]
@demurelebowski done. Table `reservation` created for `asd_db` scheme
