### ISSUE TITLE
[FEATURE] Create archive_price table in DB

### ISSUE THREAD

**Issue by demurelebowski** [demurelebowski/asd-java-intern#42]
Feature description
Create archive_price table in DB. SQL query:

CREATE TABLE archive_price (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    entity_type varchar(15) NOT NULL DEFAULT 'Reservation',
    entity_id int NOT NULL,
    name varchar(45) NOT NULL,
    state varchar(15) NOT NULL DEFAULT 'Created',
    type varchar(15) NULL,
    value double NULL,
    version timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

**Comment by rdovgan** [comment]
@demurelebowski done
