### ISSUE TITLE
[FEATURE] Create reservation_confirmation table in DB 

### ISSUE THREAD

**Issue by demurelebowski** [demurelebowski/asd-java-intern#46]
Feature description
Create reservation_confirmation table in DB. SQL query:

CREATE TABLE reservation_confirmation (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    reservation_id int NOT NULL,
    channel_partner_id int NOT NULL,
    confirmation_id varchar(45) NOT NULL,
    created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (reservation_id) REFERENCES reservation(id),
    FOREIGN KEY (channel_partner_id) REFERENCES channel_partner(id)
 );

**Comment by rdovgan** [comment]
@demurelebowski done
