### ISSUE TITLE
[FEATURE] Store quote amount in Redis

### ISSUE THREAD

**Issue by rdovgan** [demurelebowski/asd-java-intern#75]
**Feature description**
1. Implement a `quoteCalculation` and `hasReservationCollision` method
2. Implement `calculate` API and service method. Get `fromDate`, `toDate` and `productId` from request:
- Check Redis storage (see p.6)
OR
- Check if provided date are free and calculate a quote, save a result in Redis.
3. If there is a collision(s) or no prices for provided dates, zero should be stored.
4. Save quote result in Redis as hash map with next structure: `quote_result:{productId}` -> `{fromDate}:{toDate}` - > `quote`. Set expire date as 15 minutes.
5. Return a quote amount in response.
6. If there is a valid data in Redis with provided `productId`, `fromDate` and `toDate` parameters, return a corresponded result.

> `quoteCalculation(productId, fromDate, toDate)` method retrieve items from `price` table by productId and dates, calculate per day prices and sum it; then retrieve fee items with the same parameters and next filters: `fee_type` = "General", `unit` = "Per day" or "Per stay", `value_type` = "flat"; next, retrieve a fee record from DB with the same parameters with `value_type` = "percent" and multiply prices and fees result by percentFee amount
>
>  we store price data in DB with date range, and field `value` is for one day in range
> retrieve only records with state = "Created"
> full calculation formula: ((price1 + price2 + ...) + (fee1 + fee2 + ...)) * percentFee

> `hasReservationCollision(productId, fromDate, toDate)` checks all active Reservation items in provided range and return a bool value

**Requirements**
Redis module is implemented, `product-layer` dependency is imported

**Comment by demurelebowski** [comment]
> hasReservationCollision(productId, fromDate, toDate) checks all active Reservation items in provided range and return a bool value

active Reservation is a reservation where state is not 'Cancelled' ?

**Comment by rdovgan** [comment]
> > hasReservationCollision(productId, fromDate, toDate) checks all active Reservation items in provided range and return a bool value
> 
> active Reservation is a reservation where state is not 'Cancelled' ?

"Cancelled" and "Initial"

**Comment by demurelebowski** [comment]
> Save quote result in Redis as hash map with next structure: quote_result:{productId} -> {fromDate}:{toDate} - > quote. Set expire date as 15 minutes.

I need to set expire date for primaryKey {productId}, correct?
